== CUIE - Assignment 2 - TimeControl

=== Bearbeitet von

* _Kyle Egli_

=== Abgabe

* Montag, 23.5.2022, 12:00 Uhr
* Die Abgabe erfolgt durch ein "Push" auf den Master-Branch Ihres GitHub-Repositories.

=== Anwendungskontext

Das TimeControl bietet an, dass man bei League of Legends, die Jungle Monster ihrer Wiederbelebungszeit nicht selber
wissen muss und kann es jede Zeit die überbleibenden Zeit nachschauen. Solche Tools werden häufig vom normaler Spieler
benutzt um eine kleine Vorteil über die anderen Spieler zu haben. Das TimeControl soll das auf einfacher Art simulieren.
Aus zeitlichen werden hier nur 2 aus den 16 Jungle Monsters dargestellt. Die Fehlenden funktionieren vom code her genau
gleich. Es wird ein Monster vom blauen Team abgebildet und ein vom roten Team. Drück man auf "Play" beginnt die Zeit zu
laufen. Die Monsters sind erst nach 1.5 Minuten im Spiel am leben. Nach der Zeit taucht auf
die Karte ein Kreis als Symbol für die Monster auf. Clickt man auf die Monster hat man sie getötet und sie kommen
standardmässig erst in 5 Minuten wieder zum Leben. Das kann man aber umstellen in dem man auf "Stop" drückt und danach
auf "Edit". Die Zeitfeldern sind jetzt editierbar und zeigen auch an wenn die Zeit im richtigen Format ist. Drückt man
"ESC" kommt man wieder aus dem Editmodus. Drück man auf die Pfeiltasten nach Oben oder Unten wird die Zeit imkrementiert
an der Stelle des Carets. "Reset" setzt das Spiel wieder zurück auf die Defaulteinstellungen. Beim Dropdownchooser kann
man noch ColorblindModus einschalten. Das setzt alle roten Farben auf Violett und Hellblau.

=== Initiale Schritte

* Tragen Sie ihre Namen unter "Bearbeitet von" ein.
* Pushen Sie diese Änderungen sofort ins Git-Repository (z.B. via `VCS -> Commit… -> Commit & Push`)

=== Aufgabe: BusinessControl

Entwerfen und implementieren Sie das im Unterricht besprochene BusinessControl "TimeControl" auf Basis JavaFX.

* Benutzen Sie zur Umsetzung die vorgegebene Struktur mit Control, Skin und CSS.
* Beschreiben Sie im Abschnitt 'Anwendungskontext' (siehe oben) kurz für welchen spezifischen Zweck Ihr TimeControl entworfen wurde.

Es wird empfohlen, diese Aufgabe in einem 2-er Team zu bearbeiten.

=== Bewertung

* Für 3 Punkte muss das TimeControl unter 'Anwendungskontext' kurz beschrieben werden und die im Unterricht besprochenen Mindestanforderungen an ein BusinessControl erfüllt sein.
** die aktuelle Zeit kann angezeigt und verändert werden
** die Beschriftung kann definiert werden und wird geeignet visualisiert
** auf die Statuswechsel readOnly/editable, mandatory/optional, valid/invalid, konvertierbar/nicht konvertierbar wird dynamisch reagiert
** optimale Keyboardunterstützung inklusive Forgiving-Format
** optimale Maus-Unterstützung innerhalb des DropDownChoosers
* 0 Punkte gibt es
** falls das Projekt nicht komplierfähig ist
** falls die Demo-Applikation bereits beim Start abstürzt
** falls der im Unterricht erarbeitete und jeweils in Teams zur Verfügung gestellte Stand nicht deutlich erkennbar verändert wurde
** für Plagiate
** falls kein aktiver Beitrag eines der beiden Teammitglieder an der Lösung erkennbar ist
** im Zweifelsfall wird ein Code-Walkthrough durchgeführt
* In Ausnahmefällen kann es dazu kommen, dass Teammitglieder unterschiedliche Punkte erhalten.


=== Bitte beachten Sie

* Falls Sie das Assignment zu zweit bearbeiten:
** tragen Sie beide Namen unter "Bearbeitet von" ein
** arbeiten Sie ausschliesslich in einem Repository
** falls sie beide Zugang zu diesem Repository wollen: tragen Sie die zweite Person als "Collaborator" ein (auf GitHub unter "Settings -> Manage access")
** löschen Sie das nicht benötigte Repository (auf GitHub unter "Settings")
** arbeiten Sie gemeinsam und gleichzeitig an den Aufgaben (Stichwort: Pair-Programming)
** https://www.it-agile.de/wissen/agiles-engineering/pair-programming/[Pair-Programming] heisst insbesondere, dass beide Teammitglieder zu gleichen Teilen aktiv in der Entwickler-Rolle sind. Einem Entwickler lediglich bei seiner Arbeit zuzuschauen ist kein Pair-Programming.
** für "Remote Pair-Programming" ist das "Code With Me"-Plugin für IntelliJ IDEA sehr zu empfehlen
** das Aufteilen und separate Bearbeiten von Teil-Aufgaben ist nicht erwünscht
* Ausdrücklich erlaubt und erwünscht ist, dass Sie sich gegebenenfalls Hilfe holen.
Nachfragen werden zum Beispiel über den im Repository integrierten
Issue Tracker oder in MS Teams gerne beantwortet.

